name: Deploy MkDocs site
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 关键：赋予写入仓库分支权限
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装MkDocs和主题
        run: pip install mkdocs mkdocs-material

      - name: 生成静态网页
        run: mkdocs build --clean --verbose

      - name: 部署到Pages分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
