name: 自动部署博客到GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: 安装MkDocs依赖
        run: pip install mkdocs mkdocs-material
      - name: 生成静态页面并部署
        run: mkdocs gh-deploy --force